<a href="https://colab.research.google.com/github/ankurdome/AI_ML_Learnings/blob/main/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pandas**

In [1]:
import pandas as pd

In [2]:
pd.DataFrame({'A': [1, 2], 'B': [3, 4]})

A  B
0  1  3
1  2  4

In [3]:
pd.Series([1, 2, 3, 4])

0    1
1    2
2    3
3    4
dtype: int64

In [5]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
df

A  B
0  1  4
1  2  5
2  3  6

In [6]:
df.head()

A  B
0  1  4
1  2  5
2  3  6

In [7]:
df.tail()

A  B
0  1  4
1  2  5
2  3  6

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
dtypes: int64(2)
memory usage: 180.0 bytes


In [9]:
df.describe()

A    B
count  3.0  3.0
mean   2.0  5.0
std    1.0  1.0
min    1.0  4.0
25%    1.5  4.5
50%    2.0  5.0
75%    2.5  5.5
max    3.0  6.0

In [10]:
df.columns

Index(['A', 'B'], dtype='object')

In [11]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [12]:
df.shape

(3, 2)

In [13]:
df.dtypes

A    int64
B    int64
dtype: object

In [14]:
df.isnull()

A      B
0  False  False
1  False  False
2  False  False

In [15]:
df.dropna()

A  B
0  1  4
1  2  5
2  3  6

In [16]:
df.fillna(0)

A  B
0  1  4
1  2  5
2  3  6

In [17]:
df.drop(columns=['A'])

B
0  4
1  5
2  6

In [18]:
df['A'].sum()

6

In [19]:
df['A'].mean()

2.0

In [20]:
df['A'].min()

1

In [21]:
df['A'].max()

3

In [22]:
df['A'].value_counts()

A
1    1
2    1
3    1
Name: count, dtype: int64

In [23]:
df.sort_values(by='A')

A  B
0  1  4
1  2  5
2  3  6

In [24]:
df.sort_index()

A  B
0  1  4
1  2  5
2  3  6

In [25]:
df.groupby('A').sum()

B
A   
1  4
2  5
3  6

In [26]:
df.set_index('A')

B
A   
1  4
2  5
3  6

In [27]:
df.reset_index()

index  A  B
0      0  1  4
1      1  2  5
2      2  3  6

In [28]:
df.apply(lambda x: x * 2)

A   B
0  2   8
1  4  10
2  6  12

In [29]:
df.applymap(lambda x: x * 2)

<ipython-input-29-0a5972bf650b>:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x * 2)


A   B
0  2   8
1  4  10
2  6  12

In [30]:
df.rename(columns={'A': 'Ankur'})

Ankur  B
0      1  4
1      2  5
2      3  6

In [31]:
df.duplicated()

0    False
1    False
2    False
dtype: bool

In [32]:
df.drop_duplicates()

A  B
0  1  4
1  2  5
2  3  6

In [33]:
df.corr()

A    B
A  1.0  1.0
B  1.0  1.0

In [34]:
df.cov()

A    B
A  1.0  1.0
B  1.0  1.0

In [35]:
df.melt(id_vars=['A'], value_vars=['B'])

A variable  value
0  1        B      4
1  2        B      5
2  3        B      6

In [36]:
df.pivot(columns='A', values='B')

A    1    2    3
0  4.0  NaN  NaN
1  NaN  5.0  NaN
2  NaN  NaN  6.0

In [37]:
df.merge(pd.DataFrame({'A': [1, 2], 'C': [7, 8]}), on='A')

A  B  C
0  1  4  7
1  2  5  8

In [39]:
df.sample(n=2)

A  B
2  3  6
0  1  4

In [40]:
df.nunique()

A    3
B    3
dtype: int64

In [41]:
df.memory_usage()

Index    132
A         24
B         24
dtype: int64

In [42]:
df.T

0  1  2
A  1  2  3
B  4  5  6

In [43]:
df.at[1, 'A']

2

In [44]:
df.iat[1, 0]

2

In [45]:
df.loc[:, ['A']]

A
0  1
1  2
2  3

In [46]:
df.iloc[:, 0]

0    1
1    2
2    3
Name: A, dtype: int64

In [47]:
df.query('A > 1')

A  B
1  2  5
2  3  6

In [48]:
df.replace(1, 10)

A  B
0  10  4
1   2  5
2   3  6

In [49]:
df.clip(lower=2, upper=5)

A  B
0  2  4
1  2  5
2  3  5

In [50]:
df.astype(str)

A  B
0  1  4
1  2  5
2  3  6

In [51]:
df.to_numpy()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [52]:
df.to_dict()

{'A': {0: 1, 1: 2, 2: 3}, 'B': {0: 4, 1: 5, 2: 6}}

In [53]:
df.to_csv('data.csv', index=False)

In [54]:
df.to_excel('data.xlsx', index=False)

In [55]:
df.to_json()

'{"A":{"0":1,"1":2,"2":3},"B":{"0":4,"1":5,"2":6}}'

# **Numpy**

In [56]:
import numpy as np


In [57]:
np.array([1, 2, 3, 4])


array([1, 2, 3, 4])

In [58]:
np.zeros((3,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [59]:
np.ones((2,2))


array([[1., 1.],
       [1., 1.]])

In [60]:
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [61]:
np.full((2,3), 7)


array([[7, 7, 7],
       [7, 7, 7]])

In [62]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
np.random.randint(1, 10, (2,2))


array([[5, 3],
       [3, 8]])

In [65]:
arr = np.array([[1, 2], [3, 4]])
arr.shape



(2, 2)

In [66]:
arr.size


4

In [ ]:
arr.ndim
arr.dtype
arr.T

In [67]:
np.sort(arr)


array([[1, 2],
       [3, 4]])

In [68]:
np.vstack((arr, arr))


array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [69]:
np.clip(arr, 1, 3)


array([[1, 2],
       [3, 3]])

In [70]:
np.where(arr > 2, 'High', 'Low')


array([['Low', 'Low'],
       ['High', 'High']], dtype='<U4')

In [71]:
np.exp(arr)


array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [72]:
np.floor(arr)


array([[1., 2.],
       [3., 4.]])

In [74]:
np.reshape(arr, (4,1))


array([[1],
       [2],
       [3],
       [4]])